const BASE_MANTRAS = [
  "Begin with one clear step.",
  "Let the day be simple.",
  "Move with steady attention.",
  "Make room for what matters.",
  "Pause before you rush.",
  "Small progress is still progress.",
  "Choose the next useful thing.",
  "Keep your focus gentle.",
  "Start where you are.",
  "Breathe, then begin.",
  "Let enough be enough.",
  "Do one thing fully.",
  "Notice what is working.",
  "Give the day a calm shape.",
  "Meet the moment plainly.",
  "Use your energy with care.",
  "Leave space between tasks.",
  "A steady pace can carry you.",
  "Clarity grows from action.",
  "Take the kind next step.",
  "Protect a little quiet.",
  "Let the morning reset you.",
  "Return to what is real.",
  "Keep your promises small.",
  "Make today workable.",
  "Do less, but do it well.",
  "Let your attention land.",
  "Trust the next honest step.",
  "Progress can be quiet.",
  "Begin again without drama.",
  "Aim for useful, not perfect.",
  "Stay close to the present.",
  "Your pace is allowed.",
  "Clear one small corner.",
  "Let the plan stay human.",
  "Hold the day lightly.",
  "Make space to think.",
  "Use time with kindness.",
  "One task can be enough.",
  "Let calm guide the order.",
  "Choose presence over hurry.",
  "The next minute is open.",
  "Steady is a strategy.",
  "Notice, adjust, continue.",
  "Let the work breathe.",
  "You can simplify this.",
  "Keep your footing first.",
  "Return to the basics.",
  "Let patience do some work.",
  "Make a clean beginning.",
  "Find the smallest door in.",
  "Be direct and gentle.",
  "Carry only this moment.",
  "Give attention, not pressure.",
  "Let the day unfold in order.",
  "Start with the obvious.",
  "Keep the good parts visible.",
  "Enough light is enough.",
  "Leave room for repair.",
  "Let your mind unclench.",
  "Choose a sustainable pace.",
  "Make the next choice clear.",
  "Do what helps next.",
  "Stay with the signal.",
  "Let today be learnable.",
  "A clean pause is useful.",
  "Begin from steadiness.",
  "Let the task be ordinary.",
  "Keep returning to calm.",
  "Make one useful mark.",
  "Your attention is valuable.",
  "Let simple be strong.",
  "Move from care, not force.",
];

export const MANTRAS = Array.from(
  { length: 365 },
  (_, index) => BASE_MANTRAS[index % BASE_MANTRAS.length],
);

export function getDailyMantra(date: Date) {
  const start = Date.UTC(date.getUTCFullYear(), 0, 0);
  const dayOfYear = Math.floor((date.getTime() - start) / 86_400_000);
  return MANTRAS[dayOfYear % MANTRAS.length];
}
